package model;

import java.util.Date;

import model.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 26 22:24:17 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for EmpsalbydatesVO1.
     * @return EmpsalbydatesVO1
     */
    public ViewObjectImpl getEmpsalbydatesVO1() {
        return (ViewObjectImpl)findViewObject("EmpsalbydatesVO1");
    }
    
    public void createRow(String empEmail, String sal, Date from, Date to) {
        
        Number salary = Integer.parseInt(sal);
        ViewObject vo= findViewObject("EmpsalbydatesVO1");
        Row row=vo.createRow();
        row.setAttribute("EmpEmail", empEmail);
        row.setAttribute("salary", sal);
        row.setAttribute("FromDate", from);
        row.setAttribute("ToDate", to);
        vo.insertRow(row);
        getDBTransaction().commit();
        
    }
}
