package model.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 26 22:26:09 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void createRow(String empEmail, String sal, Date from, Date to);
}
