package model.client;

import java.util.Date;

import model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 26 22:26:09 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void createRow(String empEmail, String sal, Date from, Date to) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createRow",new String [] {"java.lang.String","java.lang.String","java.util.Date","java.util.Date"},new Object[] {empEmail, sal, from, to});
        return;
    }
}
